import type { AgentFiLiveSnapshot } from "./liveSnapshotService";
import { calculateLiveRiskProfile } from "./riskEngine";
import { generateLiveRecommendations } from "./recommendationEngine";

export interface LiveEnterpriseReport {
  reportTitle: string;
  snapshotId: string;
  generatedAt: string;
  network: "Solana Devnet";
  valuationNotice: "Devnet balances are test funds and have no real monetary value. USD figures, when shown, are mainnet market-price references only.";
  wallet: {
    address: string | null;
    connected: boolean;
    solBalance: number | null;
    tokenCount: number;
    transactionCount: number;
  };
  market: {
    solPriceUsd: number | null;
    change24h: number | null;
    provider: string;
  };
  riskSummary: {
    totalRiskScore: number;
    riskCategory: string;
    explanation: string;
  };
  recommendations: Array<{
    title: string;
    evidence: string;
  }>;
  disclaimer: "Generated by AgentFi — Educational prototype. Not financial advice.";
}

export function generateLiveEnterpriseReport(snapshot: AgentFiLiveSnapshot | null): LiveEnterpriseReport {
  const risk = calculateLiveRiskProfile(snapshot);
  const recs = generateLiveRecommendations(snapshot);

  const walletAddr = snapshot?.wallet?.publicKey ?? null;
  const solBal = snapshot?.wallet?.solBalance ?? null;
  const tokenCount = snapshot?.wallet?.tokenAccounts?.length ?? 0;
  const txCount = snapshot?.wallet?.recentTransactions?.length ?? 0;

  return {
    reportTitle: "AgentFi Live Enterprise Portfolio Report",
    snapshotId: snapshot?.snapshotId || `snap_${Date.now()}`,
    generatedAt: new Date().toISOString(),
    network: "Solana Devnet",
    valuationNotice:
      "Devnet balances are test funds and have no real monetary value. USD figures, when shown, are mainnet market-price references only.",
    wallet: {
      address: walletAddr,
      connected: Boolean(snapshot?.wallet?.connected),
      solBalance: solBal,
      tokenCount,
      transactionCount: txCount,
    },
    market: {
      solPriceUsd: snapshot?.market?.solUsdPrice ?? null,
      change24h: snapshot?.market?.change24hPercent ?? null,
      provider: "CoinGecko",
    },
    riskSummary: {
      totalRiskScore: risk.totalRiskScore,
      riskCategory: risk.riskCategory,
      explanation: risk.formulaExplanation,
    },
    recommendations: recs.map((r) => ({
      title: r.title,
      evidence: r.evidence,
    })),
    disclaimer: "Generated by AgentFi — Educational prototype. Not financial advice.",
  };
}
